[tool.black]
line-length = 80
target-version = ["py37", "py38"]
exclude = "((.eggs | .git | .pytest_cache | build | dist))"

[build-system]
requires = [
  "setuptools>=42",
  "wheel"
]
build-backend = "setuptools.build_meta"
